name: JaCoCo Report

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    environment: firebase
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Create private config file
        run: |
          cat <<EOF > ./app/google-services.json
          {
          "project_info": {
           "project_number": "${{ secrets.PROJECT_NUMBER }}",
           "project_id": "echotrail-6ae24",
           "storage_bucket": "echotrail-6ae24.firebasestorage.app"
          },
          "client": [
           {
             "client_info": {
               "mobilesdk_app_id": "${{ secrets.MOBILESDK_APP_ID }}",
               "android_client_info": {
                 "package_name": "com.peppe289.echotrail"
               }
             },
             "oauth_client": [],
             "api_key": [
               {
                 "current_key": "${{ secrets.CURRENT_KEY }}"
               }
             ],
             "services": {
               "appinvite_service": {
                 "other_platform_oauth_client": []
               }
             }
           }
          ],
          "configuration_version": "1"
          }
          EOF

      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew testDebugUnitTest jacocoTestReport

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/testCoverageReport/testCoverageReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
